import { RulesPreset } from './preset.js';

export const HONG_KONG_PRESET: RulesPreset = {
  id: 'hong-kong',
  name: 'Hong Kong',
  description: 'Traditional Hong Kong Mahjong — self-draw only with wild cards and GONG doubling.',
  playerCount: 4,
  flowersEnabled: false,
  minimumHan: 0,
  scoringModel: 'hong-kong',
  kiriageMangan: false,
  kazoeLimit: 'none',
  allowOpenHand: true,
  allowChi: true,
  allowPon: true,
  allowKan: true,
  allowRiichi: false,
  doubleRiichi: false,
  ippatsu: false,
  reactionPriority: ['pon', 'kan-open', 'chi'],
  atamahane: false,
  turnTimerEnabled: false,
  turnTimerSeconds: 30,
  reactionTimerSeconds: 15,
  autoSortHand: true,
  confirmDiscard: false,
  scoreDisplayVerbosity: 'standard',
  spectatorPolicy: 'allow',
  wildCardEnabled: true,
  selfDrawOnly: true,
  gongDoubles: true,
};
