import { RulesPreset } from './preset.js';

export const RIICHI_PRESET: RulesPreset = {
  id: 'riichi',
  name: 'Riichi',
  description: 'Japanese Riichi Mahjong — the most popular competitive variant worldwide.',
  playerCount: 4,
  flowersEnabled: false,
  minimumHan: 1,
  scoringModel: 'riichi',
  kiriageMangan: false,
  kazoeLimit: 'sanbaiman',
  allowOpenHand: true,
  allowChi: true,
  allowPon: true,
  allowKan: true,
  allowRiichi: true,
  doubleRiichi: true,
  ippatsu: true,
  reactionPriority: ['ron', 'kan-open', 'pon', 'chi'],
  atamahane: false,
  turnTimerEnabled: false,
  turnTimerSeconds: 30,
  reactionTimerSeconds: 15,
  autoSortHand: true,
  confirmDiscard: false,
  scoreDisplayVerbosity: 'standard',
  spectatorPolicy: 'allow',
};
